### ISSUE TITLE
Update to NET 6

### ISSUE THREAD

**Issue by Ayymoss** [RileyTheFox/CHColorEditor#5]
I gave it a quick shot, but a little too advanced for me. 

Would be better as NET6 is the latest LTS branch.

**Comment by RileyTheFox** [comment]
.NET 7 just released so this is redundant, however I see the benefit of being on an LTS branch.

Still not going to update the version however because I plan to remake this app from scratch in the future. .NET 5 might be out of support but I don't feel like an upgrade is necessary.
